# Generated by Django 5.2.7 on 2025-10-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestsellers',
            name='old_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='featured',
            name='old_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='old_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
