# Generated by Django 5.2.7 on 2025-10-14 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_bestsellers_old_price_featured_old_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='featured',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newarrivals',
            name='category',
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField(default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.category')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='BestSellers',
        ),
        migrations.DeleteModel(
            name='featured',
        ),
        migrations.DeleteModel(
            name='NewArrivals',
        ),
    ]
