# Generated by Django 5.2.7 on 2025-10-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_remove_items_tag_items_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
