# Generated by Django 5.2.7 on 2025-10-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_items_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
