# Generated by Django 5.2.7 on 2025-10-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0006_alter_items_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="ratings",
            field=models.FloatField(default=0, null=True),
        ),
    ]
