# Generated by Django 5.2.7 on 2025-10-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0007_items_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
