# Generated by Django 5.2.7 on 2025-10-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0008_items_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="featured",
        ),
    ]
