# Generated by Django 5.2.7 on 2025-10-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0009_remove_items_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="pics")),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
