# Generated by Django 5.2.7 on 2025-10-26 20:17

from django.db import migrations
from django.utils import timezone

def populate_blogs(apps, schema_editor):
    Blog = apps.get_model('WebApp', 'Blog')
    Blog.objects.create(
        title="The Timeless Tradition of Indian Pickles",
        author="Sai Ganesh",
        description="Discover the rich history and diverse flavors of Indian pickles, a culinary tradition passed down through generations. From tangy mangoes to spicy chilies, every jar tells a story.",
        image="pics/pickle_blog.jpg",
        date=timezone.now()
    )
    Blog.objects.create(
        title="Unveiling the Secrets of Authentic Indian Spices",
        author="Preetham",
        description="Explore the aromatic world of Indian spices. Learn how to identify, blend, and use them to create dishes that are bursting with flavor and fragrance.",
        image="pics/spices_blog.jpg",
        date=timezone.now()
    )
    Blog.objects.create(
        title="The Art of Making Traditional Indian Sweets",
        author="Eruvaka Team",
        description="A guide to creating mouth-watering Indian sweets at home. From the syrupy goodness of Jalebi to the delicate texture of Barfi, sweeten your life with these recipes.",
        image="pics/sweets_blog.jpg",
        date=timezone.now()
    )

class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0010_blog"),
    ]

    operations = [
        migrations.RunPython(populate_blogs),
    ]
